package views;
import models.LibroDTO;
import models.LibroDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franklyn Zarzuela
 */
public class VistaLibreriaGUI extends javax.swing.JFrame {
    
    
    
    LibroDAO libroDAO = new LibroDAO();

    /**
     * Creates new form VistaLibreriaGUI
     */
    public VistaLibreriaGUI() {
        initComponents();

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBase = new javax.swing.JPanel();
        pEntradaDatosLibros = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombreLibro = new javax.swing.JTextField();
        txtAumentoMora = new javax.swing.JTextField();
        txtPrecioDia = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecioOriginal = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtTotalGanancias = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        txtFechaCreacion = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        pListaLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control_Panel");

        pBase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BiblioSolutions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 24))); // NOI18N

        pEntradaDatosLibros.setBackground(new java.awt.Color(0, 102, 102));
        pEntradaDatosLibros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introduzca la siguiente información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtId.setEditable(false);
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtId.setPreferredSize(new java.awt.Dimension(60, 60));

        txtNombreLibro.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del Libro"));
        txtNombreLibro.setPreferredSize(new java.awt.Dimension(60, 60));

        txtAumentoMora.setBorder(javax.swing.BorderFactory.createTitledBorder("Aumento Por Mora"));
        txtAumentoMora.setPreferredSize(new java.awt.Dimension(60, 60));
        txtAumentoMora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAumentoMoraActionPerformed(evt);
            }
        });

        txtPrecioDia.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio Por Dia"));
        txtPrecioDia.setPreferredSize(new java.awt.Dimension(60, 60));

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Total"));
        txtStock.setPreferredSize(new java.awt.Dimension(60, 60));

        txtPrecioOriginal.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio Original"));
        txtPrecioOriginal.setPreferredSize(new java.awt.Dimension(60, 60));
        txtPrecioOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioOriginalActionPerformed(evt);
            }
        });

        txtUbicacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicacion"));
        txtUbicacion.setPreferredSize(new java.awt.Dimension(60, 60));
        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });

        txtTotalGanancias.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Ganancias"));
        txtTotalGanancias.setPreferredSize(new java.awt.Dimension(60, 60));
        txtTotalGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalGananciasActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVer.setText("Ver Libros");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        txtFechaCreacion.setEditable(false);
        txtFechaCreacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Creacion"));
        txtFechaCreacion.setPreferredSize(new java.awt.Dimension(60, 60));
        txtFechaCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaCreacionActionPerformed(evt);
            }
        });

        txtAutor.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del Autor"));
        txtAutor.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout pEntradaDatosLibrosLayout = new javax.swing.GroupLayout(pEntradaDatosLibros);
        pEntradaDatosLibros.setLayout(pEntradaDatosLibrosLayout);
        pEntradaDatosLibrosLayout.setHorizontalGroup(
            pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(21, 21, 21)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                        .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtPrecioDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAumentoMora, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                        .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                                .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        pEntradaDatosLibrosLayout.setVerticalGroup(
            pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEntradaDatosLibrosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAumentoMora, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(pEntradaDatosLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVer))
                .addContainerGap())
        );

        pListaLibros.setBackground(new java.awt.Color(0, 102, 102));
        pListaLibros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Libros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre del Libro", "Disponibilidad", "Precio Por Dia", "Precio Original", "Aumento Por Mora", "Stock Total", "Estado", "Columna", "Fila"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        javax.swing.GroupLayout pListaLibrosLayout = new javax.swing.GroupLayout(pListaLibros);
        pListaLibros.setLayout(pListaLibrosLayout);
        pListaLibrosLayout.setHorizontalGroup(
            pListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pListaLibrosLayout.setVerticalGroup(
            pListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListaLibrosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pBaseLayout = new javax.swing.GroupLayout(pBase);
        pBase.setLayout(pBaseLayout);
        pBaseLayout.setHorizontalGroup(
            pBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEntradaDatosLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pListaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBaseLayout.setVerticalGroup(
            pBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pListaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pEntradaDatosLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAumentoMoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAumentoMoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAumentoMoraActionPerformed

    private void txtPrecioOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioOriginalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioOriginalActionPerformed

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void txtTotalGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalGananciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalGananciasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        LibroDTO libro = new LibroDTO();
        
        String autorName = txtAutor.getText();
        double buyed_Price = Integer.parseInt(txtPrecioOriginal.getText());
        String created_at = txtFechaCreacion.getText();
        String desc_ubicacion = txtUbicacion.getText();
        int id = Integer.parseInt(txtId.getText());
        double mora_aument = Integer.parseInt(txtAumentoMora.getText());
        String title = txtNombreLibro.getText();
        double total_ganancias = Integer.parseInt(txtTotalGanancias.getText());
        int total_stock = Integer.parseInt(txtStock.getText());
        
        libro.setAutorName(autorName);
        libro.setBuyed_price(buyed_Price);
        libro.setCreated_at(created_at);
        libro.setDesc_ubicacion(desc_ubicacion);
        libro.setId(id);
        libro.setMora_aument(mora_aument);
        libro.setTitle(title);
        libro.setTotal_ganancies(total_ganancias);
        libro.setTotal_stock(total_stock);
        
        LibroDAO libroAgregado = new LibroDAO();
        int resultado = libroAgregado.agregar(libro);
            if (resultado == 1) {
                libroDAO.listar();
                // Limpiar los campos de texto después de agregar una reserva
                txtAutor.setText("");
                txtPrecioOriginal.setText("");
                txtFechaCreacion.setText("");
                txtUbicacion.setText("");
                txtId.setText("");
                txtAumentoMora.setText("");
                txtNombreLibro.setText("");
                txtTotalGanancias.setText("");
                txtStock.setText("");
            }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int fila = tblLibros.getSelectedRow();
        if (fila != -1) {
            LibroDTO libro = new LibroDTO();
            
            
            libro.setAutorName(txtAutor.getText());
            libro.setBuyed_price(Integer.parseInt(txtPrecioOriginal.getText()));
            libro.setCreated_at(txtFechaCreacion.getText());
            libro.setDesc_ubicacion(txtUbicacion.getText());
            libro.setId(Integer.parseInt(txtId.getText()));
            libro.setMora_aument(Integer.parseInt(txtAumentoMora.getText()));
            libro.setTitle(txtNombreLibro.getText());
            libro.setTotal_ganancies(Integer.parseInt(txtTotalGanancias.getText()));
            libro.setTotal_stock(Integer.parseInt(txtStock.getText()));
            
            libro.setId((int) tblLibros.getValueAt(fila, 0));
            
            LibroDAO libroActualizado = new LibroDAO();
            int resultado = libroActualizado.actualizar(libro);
            if (resultado == 1) {
                libroActualizado.listar();
                JOptionPane.showMessageDialog(null, "Libro actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la informacion del libro.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un libro para actualizar.");
        }
        
        // Limpiar los campos de texto después de agregar una reserva
                txtAutor.setText("");
                txtPrecioOriginal.setText("");
                txtFechaCreacion.setText("");
                txtUbicacion.setText("");
                txtId.setText("");
                txtAumentoMora.setText("");
                txtNombreLibro.setText("");
                txtTotalGanancias.setText("");
                txtStock.setText("");
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        LibroDAO libroEliminado = new LibroDAO();
        int fila = tblLibros.getSelectedRow();
                    if (fila >= 0) {
                        int id = (int) tblLibros.getValueAt(fila, 0);
                        int resultado = libroDAO.eliminar(id);
                        if (resultado == 1) {
                            libroDAO.listar();
                        }
                    }
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        LibroDAO verLibros = new LibroDAO();
        List<LibroDTO> libros = verLibros.listar();
        Object[] objeto = new Object [9];
        for (int i = 0; i < libros.size(); i++) {
            objeto[0] = libros.get(i).getAutorName();
            objeto[1] = libros.get(i).getBuyed_price();
            objeto[2] = libros.get(i).getCreated_at();
            objeto[3] = libros.get(i).getDaily_price();
            objeto[4] = libros.get(i).getDesc_ubicacion();
            objeto[5] = libros.get(i).getId();
            objeto[6] = libros.get(i).getMora_aument();
            objeto[7] = libros.get(i).getTitle();
            objeto[8] = libros.get(i).getTotal_ganancies();
            objeto[9] = libros.get(i).getAutorName();
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void txtFechaCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCreacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLibreriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLibreriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLibreriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLibreriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLibreriaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBase;
    private javax.swing.JPanel pEntradaDatosLibros;
    private javax.swing.JPanel pListaLibros;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAumentoMora;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreLibro;
    private javax.swing.JTextField txtPrecioDia;
    private javax.swing.JTextField txtPrecioOriginal;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalGanancias;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
