package views;
import models.LoginDAO;
import models.LoginDTO;
        
/**
 *
 * @author Franklyn Zarzuela
 */
public class VistasLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form VistasLoginGUI
     */
    public VistasLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondoLogin = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblAccess = new javax.swing.JLabel();
        btnCloseLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFondoLogin.setBackground(new java.awt.Color(0, 102, 102));
        pFondoLogin.setPreferredSize(new java.awt.Dimension(160, 160));
        pFondoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        pFondoLogin.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        lblAccess.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        lblAccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccess.setText("Acceder");
        pFondoLogin.add(lblAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        btnCloseLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete_32x32.png"))); // NOI18N
        pFondoLogin.add(btnCloseLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        getContentPane().add(pFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, 30));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, 30));

        txtPass.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        txtPass.setText("Contraseña:");
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtUser.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        txtUser.setText("Usuario:");
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistasLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccess;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JPanel pFondoLogin;
    private javax.swing.JLabel txtPass;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JLabel txtUser;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
